include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    omit_local_variable_types: ignore
    include_file_not_found: ignore
    # name of fixtures in uppercase break this rule
    non_constant_identifier_names: ignore
    # TODO try to remove this ones
    sort_child_properties_last: ignore

  exclude:
    - sample
    - test/**/**/**/*_mocks.mocks.dart
    - lib/**.g.dart

linter:
  rules:
    omit_local_variable_types: false
    use_key_in_widget_constructors: true
    prefer_const_constructors : true
    avoid_relative_lib_imports : true
    avoid_print: true
    avoid_field_initializers_in_const_classes : true
    non_constant_identifier_names: true
    avoid_void_async: true
    unawaited_futures: true
    cast_nullable_to_non_nullable: true
