name: build_time_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^2.2.3

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  auto_route: 2.3.0

# dependency_overrides:
#   auto_route: 
#     path: /Users/jeremie_yardin/dev/auto_route-2.3.0

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.1.2
 # auto_route_generator: ^2.4.1
  auto_route_generator: ^2.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
